name: Linter
on: push
jobs:
  steps:
  - uses: actions/checkout@v1
  # https://github.com/marketplace/actions/python-code-quality-and-lint
  - uses: ricardochaves/python-lint@v1.3.0
    with:
      use-pylint: false
      use-pycodestyle: false
      use-flake8: true
      use-black: true
      use-mypy: false
      use-isort: true
      # extra-flake8-options: ""
      extra-black-options: "-l 79"
      # extra-isort-options: ""
